import "./globals.css";

export const metadata = {
  title: "Lucian Bellini - Software Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "icon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  );
}
